/* MetaLife V18 — social, gamificação e central de estatísticas (itens 22–30). */
(() => {
  const P='ml_v18_';
  const owner=()=>String(localStorage.getItem('ml_user_id')||'demo');
  const k=n=>P+encodeURIComponent(owner())+'_'+n;
  const load=(n,f)=>{try{return JSON.parse(localStorage.getItem(k(n))||'null')??f}catch{return f}};
  const save=(n,v)=>localStorage.setItem(k(n),JSON.stringify(v));
  const arr=v=>Array.isArray(v)?v:[], num=v=>Number(v)||0;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const iso=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const dayOf=x=>String(x?.date||x?.day||x?.createdAt||x?.created_at||'').slice(0,10);
  const done=x=>!!(x?.done||x?.completed||x?.status==='done'||num(x?.value)>=num(x?.target||1));
  const stateSafe=()=>{try{return state}catch{return Store.load()}};
  const id=(p='v18')=>p+'_'+Date.now().toString(36)+Math.random().toString(36).slice(2,7);
  let tab='social',competitionItems=[];

  function sessions(){return window.MetaLifeV15?.sessions?.()||[]}
  function nutrition(){return window.MetaLifeV15?.nutrition?.()||{}}
  function templates(){return load('templates',[])}
  function privacy(){return load('profile_privacy',{showXp:true,showLevel:true,showAchievements:true,showWorkouts:true,showStreak:true,showChallenges:true,showWeight:false,showDiet:false,displayName:'',bio:'',publicEnabled:false})}
  function cosmetics(){return load('cosmetics',{title:'',theme:'',frame:'',badges:[]})}
  function coinLedger(){return load('coin_ledger',[])}
  function shopPurchases(){return load('shop_purchases',[])}
  function autoBackup(){return load('backup_settings',{enabled:true,intervalHours:24,lastAt:0,maxSnapshots:10})}

  function countsBetween(days){
    const end=new Date(),start=new Date(); if(days!==Infinity)start.setDate(end.getDate()-days+1); else start.setFullYear(1970);
    const s=stateSafe(),inside=x=>{const d=dayOf(x);return d&&d>=iso(start)&&d<=iso(end)};
    const foodDays=Object.keys(nutrition()).filter(d=>d>=iso(start)&&d<=iso(end)&&Object.values(nutrition()[d]||{}).length>=0);
    return {
      workouts:sessions().filter(inside).length||arr(s.workouts).filter(inside).length,
      tasks:arr(s.tasks).filter(x=>inside(x)&&done(x)).length,
      habits:arr(s.daily).filter(x=>inside(x)&&done(x)).length,
      weight:arr(s.weight).filter(inside).length,
      nutrition:new Set(foodDays).size,
      active:new Set([...sessions().filter(inside).map(dayOf),...arr(s.tasks).filter(x=>inside(x)&&done(x)).map(dayOf),...arr(s.daily).filter(x=>inside(x)&&done(x)).map(dayOf)]).size
    };
  }

  function streak(){const s=stateSafe(),days=new Set([...sessions().map(dayOf),...arr(s.daily).filter(done).map(dayOf),...arr(s.tasks).filter(done).map(dayOf)].filter(Boolean));let n=0,d=new Date();if(!days.has(iso(d)))d.setDate(d.getDate()-1);while(days.has(iso(d))){n++;d.setDate(d.getDate()-1)}return n}
  function achievementsCount(){try{return window.MetaLifeV14?.achievements?.().length||0}catch{return 0}}
  function xp(){const s=stateSafe();return num(s.unifiedProgress?.xp??s.user?.xp)}
  function level(){const s=stateSafe();return num(s.unifiedProgress?.level??s.user?.level)||1}

  function earnedCoins(){
    const s=stateSafe(),all=countsBetween(Infinity);
    return all.workouts*12+all.tasks*2+all.habits*2+all.active*3+achievementsCount()*20+Math.floor(xp()/250)*5;
  }
  function balance(){const spent=coinLedger().filter(x=>x.type==='spend').reduce((a,x)=>a+num(x.amount),0),bonus=coinLedger().filter(x=>x.type==='bonus').reduce((a,x)=>a+num(x.amount),0);return Math.max(0,earnedCoins()+bonus-spent)}

  const SHOP=[
    {id:'title_consistente',type:'title',name:'Consistente',price:120,value:'Consistente'},
    {id:'title_marombeiro',type:'title',name:'Marombeiro',price:180,value:'Marombeiro'},
    {id:'title_foco',type:'title',name:'Mestre do Foco',price:220,value:'Mestre do Foco'},
    {id:'frame_bronze',type:'frame',name:'Moldura Bronze',price:140,value:'bronze'},
    {id:'frame_neon',type:'frame',name:'Moldura Neon',price:320,value:'neon'},
    {id:'theme_midnight',type:'theme',name:'Tema Midnight',price:260,value:'midnight'},
    {id:'badge_fire',type:'badge',name:'Badge Chama',price:90,value:'🔥'},
    {id:'badge_strength',type:'badge',name:'Badge Força',price:90,value:'💪'},
    {id:'badge_diamond',type:'badge',name:'Badge Diamante',price:400,value:'💎'}
  ];
  const UNLOCKED_TITLES=[
    ['Iniciante',()=>true],['Consistente',()=>streak()>=7],['30 Dias de Foco',()=>streak()>=30],['Marombeiro',()=>countsBetween(Infinity).workouts>=50],['Centurião',()=>countsBetween(Infinity).workouts>=100],['Mestre dos Hábitos',()=>countsBetween(Infinity).habits>=100],['Executor',()=>countsBetween(Infinity).tasks>=200],['Veterano',()=>xp()>=5000]
  ];

  function templateEncode(obj){return btoa(unescape(encodeURIComponent(JSON.stringify(obj)))).replace(/=+$/,'')}
  function templateDecode(token){return JSON.parse(decodeURIComponent(escape(atob(token.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(token.length/4)*4,'=')))))}
  function exportTemplate(t){const token=templateEncode({v:1,type:'metalife-template',template:t});navigator.clipboard?.writeText(token);toast('Código do template copiado.');}
  function importTemplate(){openModal('Importar template','<form id="v18ImportTemplate"><label>Código do template<textarea name="token" rows="6" required placeholder="Cole aqui o código recebido"></textarea></label><button class="primary">Importar</button></form>')}

  async function loadCompetitions(){
    if(!localStorage.ml_token)return [];
    try{const r=await API.call('listCompetitions');competitionItems=r?.ok?arr(r.items):[];return competitionItems}catch{return []}
  }

  function profilePreview(){const p=privacy(),c=cosmetics(),name=p.displayName||stateSafe().user?.name||'Usuário',items=[];if(p.showXp)items.push(`${xp()} XP`);if(p.showLevel)items.push(`Nível ${level()}`);if(p.showStreak)items.push(`${streak()} dias de sequência`);if(p.showWorkouts)items.push(`${countsBetween(Infinity).workouts} treinos`);if(p.showAchievements)items.push(`${achievementsCount()} conquistas`);return `<section class="v18-profile ${c.frame?'frame-'+esc(c.frame):''}"><div class="v18-avatar">${esc(name.slice(0,1).toUpperCase())}</div><h2>${esc(name)}</h2>${c.title?`<span class="pill">${esc(c.title)}</span>`:''}<p>${esc(p.bio||'Evoluindo um dia de cada vez.')}</p><div class="v18-profile-stats">${items.map(x=>`<span>${esc(x)}</span>`).join('')}</div>${arr(c.badges).length?`<div class="v18-badges">${c.badges.map(x=>`<span>${x}</span>`).join('')}</div>`:''}</section>`}

  function periodStats(){return [['7 dias',7],['30 dias',30],['90 dias',90],['Ano',365],['Tudo',Infinity]].map(([label,days])=>({label,days,stats:countsBetween(days)}))}

  function snapshotPayload(){return {version:18,createdAt:new Date().toISOString(),owner:owner(),state:stateSafe(),v14:collectPrefix('ml_v14_'),v15:collectPrefix('ml_v15_'),v16:collectPrefix('ml_v16_'),v17:collectPrefix('ml_v17_'),v18:collectPrefix('ml_v18_')}}
  function collectPrefix(prefix){const out={};for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key?.startsWith(prefix)&&key.includes(encodeURIComponent(owner()))){try{out[key]=JSON.parse(localStorage.getItem(key))}catch{out[key]=localStorage.getItem(key)}}}return out}
  function snapshots(){return load('snapshots',[])}
  function createSnapshot(auto=false){const cfg=autoBackup(),list=snapshots(),payload=snapshotPayload(),entry={id:id('snap'),createdAt:payload.createdAt,auto,size:JSON.stringify(payload).length,payload};list.unshift(entry);while(list.length>cfg.maxSnapshots)list.pop();save('snapshots',list);cfg.lastAt=Date.now();save('backup_settings',cfg);return entry}
  function maybeAutoBackup(){const cfg=autoBackup();if(!cfg.enabled)return;if(Date.now()-num(cfg.lastAt)>=num(cfg.intervalHours)*3600000)try{createSnapshot(true)}catch(e){console.warn('Backup automático local falhou',e)}}
  function downloadSnapshot(s){const blob=new Blob([JSON.stringify(s.payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`metalife-backup-${s.createdAt.slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),5000)}
  function restoreSnapshot(s){if(!confirm('Restaurar este backup? Os dados locais atuais serão substituídos pelos dados do snapshot.'))return;Object.values(s.payload).filter(x=>x&&typeof x==='object'&&!Array.isArray(x)).forEach(group=>{if(group===s.payload.state)return;Object.entries(group).forEach(([key,val])=>localStorage.setItem(key,JSON.stringify(val)))});if(s.payload.state)Store.save(s.payload.state);location.reload()}

  function nav(){return `<nav class="v18-tabs">${[['social','Social+'],['templates','Templates'],['profile','Perfil'],['competition','Modo competição'],['coins','MetaCoins'],['shop','Loja'],['titles','Títulos'],['stats','Estatísticas'],['backup','Backup']].map(([i,l])=>`<button class="chip-btn ${tab===i?'selected':''}" data-v18-tab="${i}">${l}</button>`).join('')}</nav>`}
  function render(t=tab){tab=t;const host=document.getElementById('content');if(!host)return;document.getElementById('pageTitle').textContent='Social V18';host.innerHTML=`<section class="v18-page"><header class="v18-hero"><div><div class="eyebrow">METALIFE V18</div><h2>Social, gamificação e histórico</h2><p>Templates, perfil configurável, MetaCoins, títulos, competição e backups locais.</p></div><div class="v18-coins"><b>${balance()}</b><span>MetaCoins</span></div></header>${nav()}<div id="v18Panel"></div></section>`;paint()}
  async function paint(){const p=document.getElementById('v18Panel');if(!p)return;const views={
    social(){return `<div class="v18-grid"><article class="card"><h3>Desafios privados em grupo</h3><p>Use as competições existentes para criar desafios fechados por convite entre amigos.</p><button class="primary" data-v18-open-challenges>Abrir desafios e competições</button></article><article class="card"><h3>Templates compartilháveis</h3><p>Monte uma rotina, treino ou plano e compartilhe usando um código que outra pessoa pode importar.</p><button class="primary" data-v18-tab="templates">Gerenciar templates</button></article><article class="card"><h3>Perfil configurável</h3><p>Controle quais métricas aparecem no seu cartão de perfil.</p><button class="primary" data-v18-tab="profile">Configurar perfil</button></article></div>`},
    templates(){const ts=templates();return `<article class="card"><div class="v18-actions"><button class="primary" data-v18-new-template>＋ Novo template</button><button class="chip-btn" data-v18-import-template>Importar código</button></div><h3>Meus templates</h3>${ts.length?`<div class="v18-list">${ts.map(t=>`<div class="v18-row"><div><b>${esc(t.name)}</b><small>${esc(t.type)} · ${arr(t.items).length} item(ns)</small></div><div class="v18-actions"><button class="chip-btn" data-v18-share-template="${esc(t.id)}">Compartilhar</button><button class="chip-btn" data-v18-apply-template="${esc(t.id)}">Aplicar</button><button class="chip-btn" data-v18-delete-template="${esc(t.id)}">Excluir</button></div></div>`).join('')}</div>`:'<p class="muted">Nenhum template criado.</p>'}</article>`},
    profile(){const pr=privacy();return `<div class="v18-grid"><article class="card"><h3>Configurações do perfil</h3><form id="v18ProfileForm"><label>Nome de exibição<input name="displayName" value="${esc(pr.displayName)}"></label><label>Bio<textarea name="bio" rows="3">${esc(pr.bio)}</textarea></label><label class="v18-check"><input name="publicEnabled" type="checkbox" ${pr.publicEnabled?'checked':''}> Habilitar cartão de perfil compartilhável</label>${[['showXp','Mostrar XP'],['showLevel','Mostrar nível'],['showAchievements','Mostrar conquistas'],['showWorkouts','Mostrar treinos'],['showStreak','Mostrar streak'],['showChallenges','Mostrar desafios'],['showWeight','Mostrar peso'],['showDiet','Mostrar alimentação']].map(([k,l])=>`<label class="v18-check"><input name="${k}" type="checkbox" ${pr[k]?'checked':''}> ${l}</label>`).join('')}<button class="primary">Salvar perfil</button></form><p class="muted">Peso e alimentação continuam ocultos por padrão.</p></article>${profilePreview()}</div>`},
    competition(){return `<article class="card"><div class="v18-head"><div><h3>Modo competição</h3><p class="muted">Ranking e progresso com o mínimo de distração.</p></div><button class="chip-btn" data-v18-refresh-comp>Atualizar</button></div><div id="v18CompBody"><p class="muted">Carregando competições…</p></div></article>`},
    coins(){const ledger=coinLedger();return `<div class="v18-grid"><article class="card"><h3>MetaCoins</h3><div class="v18-big-coins">${balance()}</div><p>Moeda separada do XP. Você ganha MetaCoins por consistência e usa na loja.</p><div class="v18-coin-rules"><span>Treino +12</span><span>Tarefa +2</span><span>Hábito +2</span><span>Dia ativo +3</span><span>Conquista +20</span></div></article><article class="card"><h3>Movimentações</h3>${ledger.length?ledger.slice().reverse().slice(0,20).map(x=>`<div class="v18-row"><span>${new Date(x.at).toLocaleDateString('pt-BR')} · ${esc(x.note||x.type)}</span><b>${x.type==='spend'?'-':'+'}${x.amount}</b></div>`).join(''):'<p class="muted">Nenhuma movimentação manual.</p>'}</article></div>`},
    shop(){const bought=new Set(shopPurchases()),bal=balance();return `<article class="card"><h3>Loja de recompensas</h3><p>Saldo: <b>${bal} MetaCoins</b></p><div class="v18-shop">${SHOP.map(x=>`<section><span>${x.type==='badge'?x.value:x.type==='title'?'🏷':x.type==='frame'?'🖼':'🎨'}</span><b>${esc(x.name)}</b><small>${x.price} MetaCoins</small><button class="${bought.has(x.id)?'chip-btn':'primary'}" data-v18-buy="${x.id}" ${bought.has(x.id)?'disabled':''}>${bought.has(x.id)?'Comprado':'Comprar'}</button></section>`).join('')}</div></article>`},
    titles(){const c=cosmetics(),purchases=new Set(shopPurchases());const titles=UNLOCKED_TITLES.map(([name,fn])=>({name,unlocked:fn()||SHOP.some(x=>x.type==='title'&&x.value===name&&purchases.has(x.id))}));return `<article class="card"><h3>Títulos do perfil</h3><div class="v18-title-grid">${titles.map(x=>`<button class="${c.title===x.name?'selected':''}" data-v18-title="${esc(x.name)}" ${x.unlocked?'':'disabled'}><span>${x.unlocked?'🏷':'🔒'}</span><b>${esc(x.name)}</b></button>`).join('')}</div><h3>Badges equipados</h3><div class="v18-badges">${arr(c.badges).length?c.badges.map(x=>`<span>${x}</span>`).join(''):'<span class="muted">Nenhum badge equipado.</span>'}</div></article>`},
    stats(){const ps=periodStats();return `<article class="card"><h3>Central de estatísticas</h3><div class="v18-stats-table"><div class="v18-stats-head"><span>Período</span><span>Treinos</span><span>Tarefas</span><span>Hábitos</span><span>Dias ativos</span></div>${ps.map(x=>`<div><b>${x.label}</b><span>${x.stats.workouts}</span><span>${x.stats.tasks}</span><span>${x.stats.habits}</span><span>${x.stats.active}</span></div>`).join('')}</div><div class="v18-grid" style="margin-top:16px"><div class="v18-stat-card"><b>${xp()}</b><span>XP atual</span></div><div class="v18-stat-card"><b>${level()}</b><span>Nível</span></div><div class="v18-stat-card"><b>${streak()}</b><span>Streak</span></div><div class="v18-stat-card"><b>${achievementsCount()}</b><span>Conquistas</span></div></div></article>`},
    backup(){const cfg=autoBackup(),sn=snapshots();return `<div class="v18-grid"><article class="card"><h3>Backup automático local</h3><label class="v18-check"><input id="v18BackupEnabled" type="checkbox" ${cfg.enabled?'checked':''}> Criar snapshots automaticamente</label><label>Intervalo (horas)<input id="v18BackupHours" type="number" min="1" max="168" value="${cfg.intervalHours}"></label><label>Quantidade máxima<input id="v18BackupMax" type="number" min="1" max="30" value="${cfg.maxSnapshots}"></label><div class="v18-actions"><button class="primary" data-v18-backup-save>Salvar configuração</button><button class="chip-btn" data-v18-backup-now>Criar agora</button></div><p class="muted">Os snapshots ficam neste navegador. Para segurança externa, baixe um arquivo periodicamente.</p></article><article class="card"><h3>Snapshots</h3>${sn.length?sn.map(x=>`<div class="v18-row"><div><b>${new Date(x.createdAt).toLocaleString('pt-BR')}</b><small>${x.auto?'Automático':'Manual'} · ${(x.size/1024).toFixed(1)} KB</small></div><div class="v18-actions"><button class="chip-btn" data-v18-download-backup="${x.id}">Baixar</button><button class="chip-btn" data-v18-restore-backup="${x.id}">Restaurar</button></div></div>`).join(''):'<p class="muted">Nenhum snapshot criado.</p>'}</article></div>`}
  };p.innerHTML=(views[tab]||views.social)();if(tab==='competition')paintCompetitions()}

  async function paintCompetitions(){const host=document.getElementById('v18CompBody');if(!host)return;const items=await loadCompetitions();if(!host.isConnected)return;host.innerHTML=items.length?`<div class="v18-comp-grid">${items.map(c=>`<section><span class="pill">${c.cancelled?'Cancelada':c.end<iso()?'Encerrada':c.start>iso()?'Em breve':'Em andamento'}</span><h3>${esc(c.title)}</h3><p>${esc(c.start)} → ${esc(c.end)}</p><strong>${arr(c.members).filter(m=>m.status==='accepted').length} participantes</strong><button class="primary" data-v18-open-comp="${esc(c.id)}">Abrir ranking completo</button></section>`).join('')}</div>`:'<div class="v18-empty">Nenhuma competição encontrada. Crie uma em Desafios.</div>'}

  function newTemplate(){openModal('Novo template',`<form id="v18TemplateForm"><label>Nome<input name="name" required maxlength="80"></label><label>Tipo<select name="type"><option>Rotina</option><option>Treino</option><option>Planejamento</option><option>Hábitos</option></select></label><label>Itens (um por linha)<textarea name="items" rows="8" required placeholder="Ex.: Treino A\nBeber 2L de água\nRevisar tarefas"></textarea></label><button class="primary">Salvar template</button></form>`)}
  function applyTemplate(t){if(t.type==='Treino'&&window.MetaLifeV15){const plans=JSON.parse(localStorage.getItem('ml_v15_'+encodeURIComponent(owner())+'_plans')||'[]');plans.push({id:id('plan'),name:t.name,rest:90,exercises:t.items.map(name=>({exerciseId:'',name,muscle:'',sets:3,reps:'8–12',rest:90}))});localStorage.setItem('ml_v15_'+encodeURIComponent(owner())+'_plans',JSON.stringify(plans));toast('Template adicionado às fichas do V15.');return}const ag=JSON.parse(localStorage.getItem('ml_v16_'+encodeURIComponent(owner())+'_agenda')||'{}');ag[iso()]??=[];t.items.forEach((title,i)=>ag[iso()].push({id:id('ag'),day:iso(),time:'',title,kind:'template',done:false,custom:true,tags:['template'],sourceKey:'template:'+t.id+':'+i}));localStorage.setItem('ml_v16_'+encodeURIComponent(owner())+'_agenda',JSON.stringify(ag));toast('Template aplicado ao dia de hoje.')}
  function buy(item){const bought=shopPurchases();if(bought.includes(item.id))return;if(balance()<item.price){toast('MetaCoins insuficientes.');return}bought.push(item.id);save('shop_purchases',bought);const ledger=coinLedger();ledger.push({id:id('coin'),type:'spend',amount:item.price,note:item.name,at:new Date().toISOString()});save('coin_ledger',ledger);const c=cosmetics();if(item.type==='title')c.title=item.value;if(item.type==='frame')c.frame=item.value;if(item.type==='theme')c.theme=item.value;if(item.type==='badge'&&!c.badges.includes(item.value))c.badges.push(item.value);save('cosmetics',c);toast(item.name+' adquirido.');paint()}
  function installNav(){const groups=document.getElementById('navGroups');if(!groups||groups.querySelector('[data-v18-nav]'))return;const sec=document.createElement('section');sec.className='nav-group';sec.innerHTML='<h2 class="nav-group-label">Social+</h2><button type="button" class="nav-button" data-v18-nav><span aria-hidden="true">✦</span>Social V18</button>';sec.querySelector('button').onclick=()=>render('social');groups.insertBefore(sec,groups.querySelector('.nav-mobile-account')||null)}

  document.addEventListener('submit',e=>{if(e.target.id==='v18TemplateForm'){e.preventDefault();const fd=Object.fromEntries(new FormData(e.target)),ts=templates();ts.push({id:id('tpl'),name:fd.name.trim(),type:fd.type,items:fd.items.split('\n').map(x=>x.trim()).filter(Boolean),createdAt:new Date().toISOString()});save('templates',ts);closeModal();paint()}if(e.target.id==='v18ImportTemplate'){e.preventDefault();try{const obj=templateDecode(e.target.elements.token.value.trim());if(obj?.type!=='metalife-template'||!obj.template)throw Error();const ts=templates(),t={...obj.template,id:id('tpl'),importedAt:new Date().toISOString()};ts.push(t);save('templates',ts);closeModal();toast('Template importado.');paint()}catch{toast('Código de template inválido.')}}if(e.target.id==='v18ProfileForm'){e.preventDefault();const fd=Object.fromEntries(new FormData(e.target)),p={...privacy(),displayName:fd.displayName||'',bio:fd.bio||''};['publicEnabled','showXp','showLevel','showAchievements','showWorkouts','showStreak','showChallenges','showWeight','showDiet'].forEach(k=>p[k]=e.target.elements[k]?.checked||false);save('profile_privacy',p);toast('Perfil atualizado.');paint()}})
  document.addEventListener('click',e=>{const t=e.target.closest('[data-v18-tab]');if(t){tab=t.dataset.v18Tab;render();return}if(e.target.closest('[data-v18-open-challenges]')){window.show?.('Desafios');return}if(e.target.closest('[data-v18-new-template]')){newTemplate();return}if(e.target.closest('[data-v18-import-template]')){importTemplate();return}const sh=e.target.closest('[data-v18-share-template]');if(sh){const t=templates().find(x=>x.id===sh.dataset.v18ShareTemplate);if(t)exportTemplate(t);return}const ap=e.target.closest('[data-v18-apply-template]');if(ap){const t=templates().find(x=>x.id===ap.dataset.v18ApplyTemplate);if(t)applyTemplate(t);return}const del=e.target.closest('[data-v18-delete-template]');if(del&&confirm('Excluir este template?')){save('templates',templates().filter(x=>x.id!==del.dataset.v18DeleteTemplate));paint();return}if(e.target.closest('[data-v18-refresh-comp]')){paintCompetitions();return}const oc=e.target.closest('[data-v18-open-comp]');if(oc){window.show?.('Desafios');setTimeout(()=>document.querySelector(`[data-comp="open"][data-id="${CSS.escape(oc.dataset.v18OpenComp)}"]`)?.click(),600);return}const buyBtn=e.target.closest('[data-v18-buy]');if(buyBtn){const item=SHOP.find(x=>x.id===buyBtn.dataset.v18Buy);if(item)buy(item);return}const titleBtn=e.target.closest('[data-v18-title]');if(titleBtn){const c=cosmetics();c.title=titleBtn.dataset.v18Title;save('cosmetics',c);toast('Título equipado.');paint();return}if(e.target.closest('[data-v18-backup-save]')){const cfg=autoBackup();cfg.enabled=document.getElementById('v18BackupEnabled').checked;cfg.intervalHours=Math.max(1,num(document.getElementById('v18BackupHours').value));cfg.maxSnapshots=Math.max(1,num(document.getElementById('v18BackupMax').value));save('backup_settings',cfg);toast('Backup configurado.');paint();return}if(e.target.closest('[data-v18-backup-now]')){createSnapshot(false);toast('Snapshot criado.');paint();return}const dl=e.target.closest('[data-v18-download-backup]');if(dl){const s=snapshots().find(x=>x.id===dl.dataset.v18DownloadBackup);if(s)downloadSnapshot(s);return}const rs=e.target.closest('[data-v18-restore-backup]');if(rs){const s=snapshots().find(x=>x.id===rs.dataset.v18RestoreBackup);if(s)restoreSnapshot(s);return}})

  window.MetaLifeV18={render,balance,periodStats,createSnapshot,profilePreview};
  new MutationObserver(installNav).observe(document.documentElement,{subtree:true,childList:true});
  function boot(){installNav();maybeAutoBackup();setInterval(maybeAutoBackup,3600000);setInterval(installNav,1800)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
