/* MetaLife V19 — multidispositivo, offline, segurança, admin, substituições, calendário e comparações. */
(() => {
  const PREFIX='ml_v19_';
  const owner=()=>String(localStorage.getItem('ml_user_id')||'demo');
  const key=n=>PREFIX+encodeURIComponent(owner())+'_'+n;
  const load=(n,f)=>{try{return JSON.parse(localStorage.getItem(key(n))||'null')??f}catch{return f}};
  const save=(n,v)=>localStorage.setItem(key(n),JSON.stringify(v));
  const arr=v=>Array.isArray(v)?v:[],num=v=>Number(v)||0;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
  const iso=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const dayOf=x=>String(x?.date||x?.day||x?.createdAt||x?.created_at||x?.updatedAt||'').slice(0,10);
  const stateSafe=()=>{try{return state}catch{return Store.load()}};
  const deviceId=()=>{let id=localStorage.getItem('ml_device_id');if(!id){id='DEV_'+crypto.randomUUID();localStorage.setItem('ml_device_id',id)}return id};
  const deviceName=()=>{let n=localStorage.getItem('ml_device_name');if(!n){const mobile=/Android|iPhone|iPad/i.test(navigator.userAgent);n=(mobile?'Celular':'Computador')+' · '+(navigator.platform||'navegador');localStorage.setItem('ml_device_name',n)}return n};
  let tab='sync',month=new Date();

  function v15(n,f){try{return JSON.parse(localStorage.getItem('ml_v15_'+encodeURIComponent(owner())+'_'+n)||'null')??f}catch{return f}}
  function setV15(n,v){localStorage.setItem('ml_v15_'+encodeURIComponent(owner())+'_'+n,JSON.stringify(v));window.dispatchEvent(new Event('metalife-v15-change'))}
  function v16(n,f){try{return JSON.parse(localStorage.getItem('ml_v16_'+encodeURIComponent(owner())+'_'+n)||'null')??f}catch{return f}}
  function pending(){try{return JSON.parse(localStorage.getItem('ml_pending_v1_'+encodeURIComponent(owner()))||'[]')}catch{return[]}}
  function updated(x){const t=new Date(x?.updatedAt||x?.updated_at||x?.updated||x?.createdAt||x?.created_at||x?.date||0).getTime();return Number.isFinite(t)?t:0}
  function mergeItems(server,local){const map=new Map();arr(server).forEach(x=>map.set(String(x.id||''),x));arr(local).forEach(x=>{const id=String(x.id||'');if(!id)return;const remote=map.get(id);if(!remote||updated(x)>updated(remote))map.set(id,x)});return [...map.values()]}
  const dashboardMap={listDaily:'daily',listGoals:'goals',listWeight:'weight',listTasks:'tasks',listWorkouts:'workouts',listHabits:'habits',listWeeklyReviews:'weeklyReviews'};

  function installApiLayer(){
    if(!window.API||API.__v19)return;const base=API.call.bind(API);API.__v19=true;API.call=async function(action,data={}){
      const payload={...data,device_id:deviceId(),device_name:deviceName()};
      const r=await base(action,payload);
      if(action==='getDashboard'&&r?.ok&&r.sections){const s=stateSafe();Object.entries(dashboardMap).forEach(([a,k])=>{if(r.sections[a]?.ok)r.sections[a].items=mergeItems(r.sections[a].items,s[k])});}
      return r;
    };
    if(window.Sync?.save&&!Sync.__v19){const raw=Sync.save.bind(Sync);Sync.__v19=true;Sync.save=(action,data={})=>{const d=JSON.parse(JSON.stringify(data||{}));if(d.item&&typeof d.item==='object'){d.item.updatedAt=new Date().toISOString();d.item.device_id=deviceId();d.item.record_version=num(d.item.record_version)+1}return raw(action,d)};}
  }
  async function apiV19(action,data={}){const r=await API.call(action,data);if(!r?.ok)throw Error(r?.error||'Não foi possível concluir.');return r}
  async function registerDevice(){if(!localStorage.ml_token||navigator.onLine===false)return;try{await apiV19('v19RegisterDevice')}catch(e){if(!/Ação inválida/i.test(e.message))console.warn(e)}}
  async function heartbeat(){if(!localStorage.ml_token||document.hidden||navigator.onLine===false)return;try{await apiV19('v19SyncHeartbeat')}catch{}}

  function events(){const s=stateSafe(),ev=[];const add=(day,type,title,icon,value='')=>{if(day)ev.push({day,type,title,icon,value})};arr(s.workouts).forEach(x=>add(dayOf(x),'Treino',x.name||x.title||'Treino','🏋'));arr(s.weight).forEach(x=>add(dayOf(x),'Peso',`${x.value??x.weight??'—'} kg`,'⚖'));arr(s.tasks).forEach(x=>add(dayOf(x),'Tarefa',x.title||x.name||'Tarefa',x.done||x.completed?'✓':'○'));arr(s.daily).forEach(x=>add(dayOf(x),'Meu Dia',x.title||x.name||'Registro',x.done||x.completed?'●':'○'));arr(s.goals).forEach(x=>add(dayOf(x),'Meta',x.title||x.name||'Meta','◎'));const n=v15('nutrition',{});Object.keys(n).forEach(d=>{const items=arr(n[d]?.meals).flatMap(m=>arr(m.items));if(items.length)add(d,'Alimentação',`${items.length} alimento(s)`,'🥗')});arr(v15('sessions',[])).forEach(x=>add(x.date,'Treino',x.name||'Treino V15','🏋'));arr(v16('sleep',[])).forEach(x=>add(x.day,'Sono',`${num(x.hours).toFixed(1)} h`,'🌙'));arr(v16('body',[])).forEach(x=>add(x.day,'Corpo','Medidas corporais','◌'));return ev.sort((a,b)=>b.day.localeCompare(a.day))}
  function metrics(start,end){const e=events().filter(x=>x.day>=start&&x.day<=end),s=stateSafe(),w=arr(s.weight).filter(x=>dayOf(x)>=start&&dayOf(x)<=end),n=v15('nutrition',{}),days=[];for(const d of Object.keys(n))if(d>=start&&d<=end)days.push(d);let kcal=0,protein=0;days.forEach(d=>arr(n[d]?.meals).flatMap(m=>arr(m.items)).forEach(x=>{kcal+=num(x.kcal);protein+=num(x.p)}));return{days:new Set(e.map(x=>x.day)).size,workouts:e.filter(x=>x.type==='Treino').length,tasks:e.filter(x=>x.type==='Tarefa'&&x.icon==='✓').length,foodDays:days.length,kcal:Math.round(kcal),protein:Math.round(protein),weightDelta:w.length>1?num(w.at(-1).value??w.at(-1).weight)-num(w[0].value??w[0].weight):null}}

  function nav(){return `<nav class="v19-tabs">${[['sync','Dispositivos'],['security','Segurança'],['admin','Admin'],['substitutions','Substituições'],['calendar','Calendário'],['compare','Comparar']].map(([i,l])=>`<button class="chip-btn ${tab===i?'selected':''}" data-v19-tab="${i}">${l}</button>`).join('')}</nav>`}
  function render(t=tab){tab=t;const host=document.getElementById('content');if(!host)return;document.getElementById('pageTitle').textContent='Sistema V19';host.innerHTML=`<section class="v19-page"><header class="v19-hero"><div><div class="eyebrow">METALIFE V19</div><h2>Sincronização & controle</h2><p>Multidispositivo, modo offline, segurança, administração e análises unificadas.</p></div><div class="v19-online ${navigator.onLine?'on':'off'}"><b>${navigator.onLine?'Online':'Offline'}</b><span>${pending().length} pendência(s)</span></div></header>${nav()}<div id="v19Panel"></div></section>`;paint()}
  async function paint(){const p=document.getElementById('v19Panel');if(!p)return;if(tab==='sync'){p.innerHTML=syncHtml();loadSessions();return}if(tab==='security'){p.innerHTML=securityHtml();loadSessions('v19SecuritySessions');return}if(tab==='admin'){p.innerHTML='<article class="card"><h3>Painel administrativo</h3><div id="v19Admin">Carregando…</div></article>';loadAdmin();return}if(tab==='substitutions'){p.innerHTML=substitutionsHtml();return}if(tab==='calendar'){p.innerHTML=calendarHtml();return}if(tab==='compare'){p.innerHTML=compareHtml();return}}
  function syncHtml(){const q=pending(),last=load('last_sync',null);return `<div class="v19-grid"><article class="card"><h3>Este aparelho</h3><div class="v19-device"><span>▣</span><div><b>${esc(deviceName())}</b><small>${esc(deviceId().slice(0,18))}…</small></div></div><p>Status: <b>${navigator.onLine?'conectado':'offline'}</b></p><p>Fila local: <b>${q.length} alteração(ões)</b></p><p>Última confirmação: <b>${last?new Date(last).toLocaleString('pt-BR'):'—'}</b></p><div class="v19-actions"><button class="primary" data-v19-sync>Sincronizar agora</button><button class="chip-btn" data-v19-rename>Renomear aparelho</button></div></article><article class="card"><h3>Como funciona</h3><p>Alterações são gravadas primeiro neste aparelho. Sem internet, ficam na fila e são enviadas quando a conexão voltar.</p><p>Registros novos recebem <code>updatedAt</code>, versão e identificador do aparelho para reduzir sobrescritas entre dispositivos.</p></article></div><article class="card"><h3>Sessões da conta</h3><div id="v19Sessions">Consultando servidor…</div></article>`}
  function securityHtml(){return `<div class="v19-grid"><article class="card"><h3>Segurança da conta</h3><p>Use esta área para revisar aparelhos e encerrar sessões desconhecidas.</p><button class="danger" data-v19-logout-all>Sair de todos os aparelhos</button><p class="muted">Isso invalida inclusive a sessão atual.</p></article><article class="card"><h3>Proteções ativas</h3><p>✓ sessão expira no servidor<br>✓ redefinir senha invalida sessões antigas<br>✓ limite de tentativas de recuperação<br>✓ V19 adiciona bloqueio temporário após tentativas repetidas de login</p></article></div><article class="card"><h3>Aparelhos conectados</h3><div id="v19SecuritySessions">Carregando…</div></article>`}
  async function loadSessions(target='v19Sessions'){const host=document.getElementById(target);if(!host)return;try{const r=await apiV19('v19ListSessions');host.innerHTML=r.items?.length?r.items.map(x=>`<div class="v19-row"><div><b>${esc(x.device_name||'Dispositivo')}</b><small>${x.current?'Sessão atual · ':''}último uso ${new Date(x.last_seen||x.created_at).toLocaleString('pt-BR')} · expira ${new Date(x.expires_at).toLocaleDateString('pt-BR')}</small></div>${x.current?'<span class="pill">Atual</span>':`<button class="chip-btn" data-v19-revoke="${esc(x.id)}">Encerrar</button>`}</div>`).join(''):'<p>Nenhuma sessão ativa.</p>'}catch(e){host.innerHTML=`<div class="v19-warning">O frontend V19 está instalado. Para sessões multidispositivo no servidor, publique o Code.gs V19 no Apps Script. <small>${esc(e.message)}</small></div>`}}
  async function loadAdmin(){const host=document.getElementById('v19Admin');if(!host)return;try{const r=await apiV19('v19AdminDashboard');host.innerHTML=`<div class="v19-kpis"><div><b>${r.users_total}</b><span>usuários</span></div><div><b>${r.users_active}</b><span>ativos</span></div><div><b>${r.new_7d}</b><span>novos 7 dias</span></div><div><b>${r.new_30d}</b><span>novos 30 dias</span></div><div><b>${r.active_sessions}</b><span>sessões ativas</span></div><div><b>${r.audit_events}</b><span>eventos auditados</span></div></div><p class="muted">Build backend: ${esc(r.build||'—')}</p><button class="chip-btn" data-v19-admin-users>Ver usuários recentes</button><div id="v19AdminUsers"></div>`}catch(e){host.innerHTML=`<div class="v19-warning"><b>Admin protegido pelo servidor.</b><p>${esc(e.message)}</p><p>Para liberar seu usuário como administrador, a coluna <code>tipo</code> na aba USUARIOS precisa ser <code>admin</code>.</p></div>`}}
  function substitutionsHtml(){const ex=v15('exercises',[]),plans=v15('plans',[]);return `<article class="card"><h3>Substituição inteligente de exercícios</h3><p class="muted">As alternativas são filtradas pelo mesmo grupo muscular. Você decide a troca; o histórico anterior não é alterado.</p>${plans.length?plans.map(pl=>`<section class="v19-plan"><h4>${esc(pl.name)}</h4>${arr(pl.exercises).map((pe,i)=>{const cur=ex.find(x=>x.id===pe.exerciseId)||pe,alts=ex.filter(x=>x.id!==cur.id&&String(x.muscle||'').toLowerCase()===String(cur.muscle||pe.muscle||'').toLowerCase());return `<div class="v19-row"><div><b>${esc(cur.name||pe.name)}</b><small>${esc(cur.muscle||pe.muscle||'Sem grupo')}</small></div>${alts.length?`<select data-v19-sub-select="${esc(pl.id)}|${i}"><option value="">Substituir por…</option>${alts.map(a=>`<option value="${esc(a.id)}">${esc(a.name)}</option>`).join('')}</select>`:'<span class="muted">Sem alternativa cadastrada</span>'}</div>`}).join('')}</section>`).join(''):'<p>Crie fichas e exercícios no Fitness V15.</p>'}</article>`}
  function calendarHtml(){const y=month.getFullYear(),m=month.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),pad=(first.getDay()+6)%7,ev=events(),cells=[];for(let i=0;i<pad;i++)cells.push('<div></div>');for(let d=1;d<=days;d++){const day=iso(new Date(y,m,d)),all=ev.filter(x=>x.day===day),icons=[...new Set(all.map(x=>x.icon))].slice(0,5);cells.push(`<button class="v19-day ${all.length?'has':''}" data-v19-day="${day}"><b>${d}</b><small>${icons.join(' ')}</small><i>${all.length||''}</i></button>`)}return `<article class="card"><div class="v19-month-head"><button class="chip-btn" data-v19-month="-1">←</button><h3>${month.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</h3><button class="chip-btn" data-v19-month="1">→</button></div><div class="v19-week-head">${['Seg','Ter','Qua','Qui','Sex','Sáb','Dom'].map(x=>`<span>${x}</span>`).join('')}</div><div class="v19-calendar">${cells.join('')}</div></article>`}
  function compareHtml(){const today=iso(),d=new Date();d.setDate(d.getDate()-29);const a=load('compare_a',{start:iso(d),end:today}),b=load('compare_b',(()=>{const e=new Date(d);e.setDate(e.getDate()-1);const s=new Date(e);s.setDate(s.getDate()-29);return{start:iso(s),end:iso(e)}})()),ma=metrics(a.start,a.end),mb=metrics(b.start,b.end);const row=(l,ka,fmt=v=>v)=>`<div class="v19-compare-row"><span>${l}</span><b>${fmt(ma[ka])}</b><b>${fmt(mb[ka])}</b></div>`;return `<article class="card"><h3>Comparação personalizada de períodos</h3><div class="v19-periods"><fieldset><legend>Período A</legend><input data-v19-range="a|start" type="date" value="${a.start}"><input data-v19-range="a|end" type="date" value="${a.end}"></fieldset><fieldset><legend>Período B</legend><input data-v19-range="b|start" type="date" value="${b.start}"><input data-v19-range="b|end" type="date" value="${b.end}"></fieldset></div><div class="v19-compare-head"><span>Métrica</span><b>A</b><b>B</b></div>${row('Dias ativos','days')}${row('Treinos','workouts')}${row('Tarefas concluídas','tasks')}${row('Dias com alimentação','foodDays')}${row('Calorias registradas','kcal',v=>Number(v).toLocaleString('pt-BR'))}${row('Proteína registrada','protein',v=>Number(v).toLocaleString('pt-BR')+' g')}${row('Variação de peso','weightDelta',v=>v==null?'—':`${v>0?'+':''}${v.toFixed(1)} kg`)}</article>`}

  function installNav(){const groups=document.getElementById('navGroups');if(!groups||groups.querySelector('[data-v19-nav]'))return;const sec=document.createElement('section');sec.className='nav-group';sec.innerHTML='<h2 class="nav-group-label">Sistema</h2><button type="button" class="nav-button" data-v19-nav><span aria-hidden="true">⚙</span>Sistema V19</button>';sec.querySelector('button').onclick=()=>render('sync');groups.insertBefore(sec,groups.querySelector('.nav-mobile-account')||null)}
  async function syncNow(){const btn=document.querySelector('[data-v19-sync]');if(btn)btn.disabled=true;try{if(navigator.onLine===false)throw Error('Sem conexão. As alterações continuam guardadas no aparelho.');await (Sync.flushNow?.()||Sync.flush?.());await registerDevice();save('last_sync',new Date().toISOString());toast('Sincronização solicitada.');paint()}catch(e){toast(e.message)}finally{if(btn)btn.disabled=false}}
  function localLogout(){localStorage.removeItem('ml_token');location.reload()}

  document.addEventListener('change',e=>{const sub=e.target.closest('[data-v19-sub-select]');if(sub&&sub.value){const [pid,index]=sub.dataset.v19SubSelect.split('|'),plans=v15('plans',[]),plan=plans.find(x=>String(x.id)===pid),ex=v15('exercises',[]).find(x=>String(x.id)===sub.value);if(plan&&ex){const old=plan.exercises[num(index)];plan.exercises[num(index)]={...old,exerciseId:ex.id,name:ex.name,muscle:ex.muscle,substitutedFrom:old.name||''};setV15('plans',plans);toast('Exercício substituído na ficha.');paint()}return}const r=e.target.closest('[data-v19-range]');if(r){const [which,field]=r.dataset.v19Range.split('|'),obj=load('compare_'+which,{start:'',end:''});obj[field]=r.value;if(obj.start&&obj.end&&obj.start>obj.end){toast('A data inicial deve ser anterior à final.');return}save('compare_'+which,obj);paint()}});
  document.addEventListener('click',async e=>{const t=e.target.closest('[data-v19-tab]');if(t){render(t.dataset.v19Tab);return}if(e.target.closest('[data-v19-sync]')){syncNow();return}if(e.target.closest('[data-v19-rename]')){const n=prompt('Nome deste aparelho:',deviceName());if(n?.trim()){localStorage.setItem('ml_device_name',n.trim().slice(0,120));registerDevice();paint()}return}const rev=e.target.closest('[data-v19-revoke]');if(rev){try{await apiV19('v19RevokeSession',{session_id:rev.dataset.v19Revoke});toast('Sessão encerrada.');loadSessions();loadSessions('v19SecuritySessions')}catch(x){toast(x.message)}return}if(e.target.closest('[data-v19-logout-all]')){if(!confirm('Encerrar todas as sessões da conta? Você precisará entrar novamente.'))return;try{await apiV19('v19LogoutAllSessions');localLogout()}catch(x){toast(x.message)}return}if(e.target.closest('[data-v19-admin-users]')){const h=document.getElementById('v19AdminUsers');h.textContent='Carregando…';try{const r=await apiV19('v19AdminUsers');h.innerHTML=r.items.map(x=>`<div class="v19-row"><div><b>${esc(x.name)}</b><small>${esc(x.email)} · ${esc(x.role)} · ${esc(x.status)}</small></div><span>${new Date(x.created_at).toLocaleDateString('pt-BR')}</span></div>`).join('')}catch(x){h.textContent=x.message}return}const mm=e.target.closest('[data-v19-month]');if(mm){month.setMonth(month.getMonth()+num(mm.dataset.v19Month));paint();return}const day=e.target.closest('[data-v19-day]');if(day){const es=events().filter(x=>x.day===day.dataset.v19Day);openModal('Dia '+new Date(day.dataset.v19Day+'T12:00:00').toLocaleDateString('pt-BR'),es.length?es.map(x=>`<div class="v19-row"><span>${x.icon}</span><div><b>${esc(x.title)}</b><small>${esc(x.type)}</small></div></div>`).join(''):'<p>Nenhum registro.</p>');return}});
  window.addEventListener('online',()=>{heartbeat();document.querySelector('.v19-online')&&render(tab)});window.addEventListener('offline',()=>{document.querySelector('.v19-online')&&render(tab)});window.addEventListener('metalife-data-saved',()=>save('last_sync',new Date().toISOString()));
  window.MetaLifeV19={render,events,metrics,deviceId,deviceName};
  function boot(){installApiLayer();installNav();registerDevice();setInterval(()=>{installApiLayer();installNav();heartbeat()},60000);new MutationObserver(()=>{installNav()}).observe(document.body,{subtree:true,childList:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
